# ICN Programming Course

<p align="center">
    <img width="500" alt="image" src="https://github.com/Lenakeiz/ICN_Programming_Course/blob/main/Images/cog_neuro_logo_blue_png_0.png?raw=true">
</p>

---

# **WEEK 3** - Control Flow, Dictionaries

## Control Flow 
Control flow allows us to direct the execution of our code based on conditions or to repeat actions. This is essential for making decisions and processing collections of data.


### 1. Conditional Logic (`if`, `elif`, `else`)

`if` statements let your program choose different actions based on **conditions** that evaluate to `True` or `False`.
You can chain multiple checks with `elif` (else-if), and provide a fallback with `else`.

**How it runs**
1. Evaluate the `if` condition. If `True`, run its indented block and **skip** the rest.
2. Otherwise, evaluate the first `elif`. If `True`, run its block and **skip** the rest.
3. Continue through any further `elif`s.
4. If none matched and there’s an `else`, run the `else` block.

**Common comparisons**
- Equality / inequality: `==`, `!=`
- Numeric comparisons: `<`, `<=`, `>`, `>=`
- Boolean operators: `and`, `or`, `not` *(to combine conditions similar to what we saw earlier with NumPy fancy indexing)*
- Aggregating multiple checks: `any()` / `all()` — Use `any()` and `all()` **inside the condition of an `if`/`elif`** to summarise many checks into a single True/False decision.
- Membership: `in`, `not in` *(works with strings, lists, etc)*

**Truthy / falsy values**
- Falsy: `False`, `None`, `0`, `0.0`, `''` (empty string), `[]`
- Everything else is truthy.  
  This means `if my_list:` runs only when `my_list` is **non-empty**.

In [ ]:
membrane_potential = -60 # mV, change to see different outputs
firing_threshold = -55 # mV

# Use an if-else structure to simulate the neuron's state based on potential
if membrane_potential >= firing_threshold:
    print("Neuron fires an action potential!")
else:
    print("Neuron is polarized.")

Current membrane potential: -60 mV
Firing threshold: -55 mV
Neuron is polarized.


In [ ]:
import numpy as np

# Simulate whether two neurons are firing in the same time bin
# Draw two uniform random numbers in [0, 1); treat > threshold as a spike
u_A = np.random.rand()
u_B = np.random.rand()
threshold = 0.5  # excitability threshold (probability of firing in this bin)

if (u_A > threshold) and (u_B > threshold):
    print("Both neurons fired in this time bin!")
elif (u_A > threshold) and (u_B <= threshold):
    print("Neuron A fired; Neuron B was silent.")
elif (u_A <= threshold) and (u_B > threshold):
    print("Neuron B fired; Neuron A was silent.")
else:
    print("Both neurons were silent in this time bin.")

Neuron A fired; Neuron B was silent.


In [19]:
import numpy as np
bad_trials = np.array([3, 7, 12]) 
trial = 7
if trial in bad_trials:
    print(f"Skip trial {trial}")

Skip trial 7


In [36]:
role = "Student"
if role.lower() == "student":
    print("Welcome, student.")

filename = "subject_01_events.csv"
if filename.startswith("subject_") and filename.endswith(".csv"):
    print("CSV for a subject file")

user_input = "   "
if not user_input.strip():
    print("No meaningful input provided")

Welcome, student.
CSV for a subject file
No meaningful input provided


In [32]:
import numpy as np
signal = np.array([0.2, 0.9, 0.4])
if np.any(signal > 0.8):
    print("High value detected")
if np.all(signal >= 0.0):
    print("No negative values")

High value detected
No negative values


In [ ]:
text = "The hippocampus contains place cells."
keywords_any = np.array(["hippocampus", "prefrontal cortex"])
if any(k in text.lower() for k in keywords_any):
    print("Found at least one region of interest")

keywords_all = np.array(["hippocampus", "place"])
if all(k in text.lower() for k in keywords_all):
    print("Both 'hippocampus' and 'place' are mentioned")

Found at least one region of interest
Both 'hippocampus' and 'memory' are mentioned



### 1. Iterating (For Loop)

If you want to execute the same piece of code multiple times, you can make use of a `for` loop. 
This will execute whatever code is held within the `for` block.
That is, the loop counter variable ('count' in the example below) is initialised at some value (0 in the example below), and the code within the indented block is then executed 'for' that value, then the loop counter variable moves on to the next value in list of values that have been assigned to it, and the code is executed again, and so on, until the loop counter variable reaches the last value that has been assigned to it (10, in the example below).

**In Python specifically:**
- Use `range(start, stop, step)` for basic counted loops (note: `stop` is *exclusive*).
  - `range(stop)`: 0 up to (but not including) `stop`.
  - `range(start, stop)`: `start` up to (but not including) `stop`.
  - `range(start, stop, step)`: as above, advancing by `step`.
- Use `enumerate(sequence, start=0)` when you need both the index *and* the element while iterating. It yields `(index, item)` pairs; set `start` to change the starting index.

You can also use `for` loops to iterate over sequences, such as lists or numpy arrays. However depending on the case using fancy indexing (discussed earlier) might be a more efficient solution.

There is also an `else` statement for the `for` loop and gets executed only when the loop finish completely its execution.


In [7]:
number_list = range(1, 11)
for number in number_list:
    print(number)

1
2
3
4
5
6
7
8
9
10


In [4]:
import numpy as np

reaction_times_per_trial = np.array([450, 390, 510, 420, 480, 530])

for i, rt in enumerate(reaction_times_per_trial, start=1):
    print(f"Trial {i}: {rt} ms")

Trial 1: 450 ms
Trial 2: 390 ms
Trial 3: 510 ms
Trial 4: 420 ms
Trial 5: 480 ms
Trial 6: 530 ms


In [5]:
import numpy as np
experimental_conditions = np.array(['stim_A', 'stim_B', 'baseline', 'stim_A', 'stim_C'])

# Use enumerate with start=1 to get trial numbers starting from 1
for trial_number, condition in enumerate(experimental_conditions, start=1):
    print(f"  Trial {trial_number}: Condition is '{condition}'")

  Trial 1: Condition is 'stim_A'
  Trial 2: Condition is 'stim_B'
  Trial 3: Condition is 'baseline'
  Trial 4: Condition is 'stim_A'
  Trial 5: Condition is 'stim_C'


Inside the `for` block you can perform any operations you need — e.g., compute deviations from the mean, apply conditional logic, update running totals, build lists/dictionaries, or print formatted summaries.

The loop gives you both the index and the value when using `enumerate`.

In [ ]:
import numpy as np
reaction_times = np.array([450, 390, 510, 420, 480, 530])

mean_rt = np.mean(reaction_times)
print(f"Mean RT: {mean_rt:.1f} ms")

for i, rt in enumerate(reaction_times, start=1):
    # Inside the loop: do all the per-trial operations you need
    diff = rt - mean_rt                 # compute deviation
    # (you could also update accumulators, append to lists, etc.)

    print(f"Trial {i:02d}: {rt} ms (Δ from mean: {diff:+.1f} ms)")

Mean RT: 463.3 ms
Trial 01: 450 ms (Δ from mean: -13.3 ms)
Trial 02: 390 ms (Δ from mean: -73.3 ms)
Trial 03: 510 ms (Δ from mean: +46.7 ms)
Trial 04: 420 ms (Δ from mean: -43.3 ms)
Trial 05: 480 ms (Δ from mean: +16.7 ms)
Trial 06: 530 ms (Δ from mean: +66.7 ms)


You can nest loops by adding a `for` loop inside another to repeat a set of operations across combinations of values or to access each single element of a matrix.

Nested loops let you systematically process **combinations of indices or items**—one dimension varying inside another. They’re useful whenever the task naturally has **two (or more) levels of iteration**, such as rows × columns, subjects × conditions, time × channels, or any pairwise comparisons.

**Pros**
- _Complete coverage:_ Guarantees every combination is visited exactly once, avoiding missed cases.
- _Local context:_ Inside the inner loop you have both indices/items, so you can apply conditional logic, accumulate statistics, or build structures (lists/dicts/arrays) as you go.
- _Clarity of intent:_ Mirrors the conceptual structure of the problem (e.g., “for each subject, for each condition…”).

**Cons**
- _Time complexity:_ Two nested loops are typically $\mathcal{O}(n \times m)$; this can be slow for large $n, m$.
- _Vectorisation:_ In **NumPy vectorised operations** you can usually achieve the same results but in a faster way.

In [ ]:
import numpy as np
# We compute the product of every pair of integers from 1 to 10 and store the results in a 10×10 matrix.

# Pre-allocate a 10x10 integer array
products = np.zeros((10, 10), dtype=int)

# Fill via nested loops (1..10 inclusive)
for i in range(1, 11):
    for j in range(1, 11):
        products[i - 1, j - 1] = i * j

print(products)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [ ]:
import numpy as np
# Simulate a connectivity matrix for a network of 5 neurons
# Matrix size is 5x5 (5 postsynaptic neurons x 5 presynaptic neurons)
# A non-zero value indicates a connection; the value could represent synaptic weight
# For simplicity, let's use values where 0 means no connection, positive means excitatory, negative means inhibitory.
connectivity_matrix = np.array([
    [0.0, 0.8, 0.0, -0.3, 0.0], 
    [0.5, 0.0, 0.2, 0.0, 0.7], 
    [0.0, -0.6, 0.0, 0.4, 0.0], 
    [0.1, 0.0, 0.9, 0.0, -0.2],  
    [0.0, 0.3, 0.0, 0.5, 0.0]
])

# We are getting the number of postsynaptic (row) neurons in our connectivity matrix. 
# .shape returns a n-elements array of dimensions of the array: (n_rows, n_cols) for 2D arrays, (n_x, n_y, n_z) for 3D, and so on.
num_post_synaptic_neurons = connectivity_matrix.shape[0] # Number of neurons (rows or columns)
num_pre_synaptic_neurons = connectivity_matrix.shape[1] # Number of neurons (rows or columns)

# Outer loop: Iterate through each postsynaptic neuron (rows)
for post_neuron_index in range(num_post_synaptic_neurons):
    print(f"\n--- Analyzing connections to Postsynaptic Neuron {post_neuron_index + 1} ---")

    # Inner loop: Iterate through each presynaptic neuron (columns)
    for pre_neuron_index in range(num_pre_synaptic_neurons):
        # Get the connection strength from presynaptic to postsynaptic neuron
        connection_strength = connectivity_matrix[post_neuron_index, pre_neuron_index]

        # Print details about the connection
        print(f"  Connection from Neuron {pre_neuron_index + 1} (Presynaptic) to Neuron {post_neuron_index + 1} (Postsynaptic):")
        print(f"    Strength: {connection_strength:.2f}")


--- Analyzing connections to Postsynaptic Neuron 1 ---
  Connection from Neuron 1 (Presynaptic) to Neuron 1 (Postsynaptic):
    Strength: 0.00
  Connection from Neuron 2 (Presynaptic) to Neuron 1 (Postsynaptic):
    Strength: 0.80
  Connection from Neuron 3 (Presynaptic) to Neuron 1 (Postsynaptic):
    Strength: 0.00
  Connection from Neuron 4 (Presynaptic) to Neuron 1 (Postsynaptic):
    Strength: -0.30
  Connection from Neuron 5 (Presynaptic) to Neuron 1 (Postsynaptic):
    Strength: 0.00

--- Analyzing connections to Postsynaptic Neuron 2 ---
  Connection from Neuron 1 (Presynaptic) to Neuron 2 (Postsynaptic):
    Strength: 0.50
  Connection from Neuron 2 (Presynaptic) to Neuron 2 (Postsynaptic):
    Strength: 0.00
  Connection from Neuron 3 (Presynaptic) to Neuron 2 (Postsynaptic):
    Strength: 0.20
  Connection from Neuron 4 (Presynaptic) to Neuron 2 (Postsynaptic):
    Strength: 0.00
  Connection from Neuron 5 (Presynaptic) to Neuron 2 (Postsynaptic):
    Strength: 0.70

--- An

### 2. Iterating (While Loop)

`while` loops are another type of control flow structure used for repeated execution of a block of code.

Unlike `for` loops, which typically iterate over a fixed sequence, `while` loops continue to execute as long as a specific condition remains `True`.

This is useful when you don't know in advance how many times you need to loop, and the continuation of the loop depends on the state of a variable or condition that changes within the loop.

> ⚠️ Watch out for infinite loops ⚠️
When using `while` loops, it is crucial to ensure that the condition controlling the loop will eventually become `False`. If the condition *never* becomes `False`, the loop will continue to execute indefinitely, resulting in an **infinite loop**. An infinite loop will cause your program to freeze and become unresponsive, potentially requiring you to interrupt or restart the execution environment 


In [ ]:
# Simulate a simple neuron model where the membrane potential increases over time until it reaches a firing threshold.

# Initial membrane potential (mV)
membrane_potential = -70.0
# Firing threshold (mV)
firing_threshold = -55.0
# Input rate in mV per ms (treated as a rate)
input_rate_mV_per_ms = 1.0
# Simulated time step (ms)
dt_ms = 1.0

print(f"Starting membrane potential simulation from {membrane_potential} mV.")
print(f"Firing threshold: {firing_threshold} mV")

time_elapsed_ms = 0
max_steps = 100000  # safety cap to prevent infinite loops

while membrane_potential < firing_threshold and time_elapsed_ms < max_steps:
    # Update membrane potential based on rate and timestep
    membrane_potential += input_rate_mV_per_ms * dt_ms
    time_elapsed_ms += dt_ms

print (f"Neuron fired after {time_elapsed_ms} ms at membrane potential {membrane_potential} mV.")

### Using `break` to finish iterations

`break` **immediately exits the nearest (innermost) loop**, skipping any remaining iterations and jumping to the first statement **after** that loop. It’s useful when:
- You have found what you were looking for. Save execution time.
- You detect an error and must stop the loop.
- You enforce a safety cap to prevent infinite/long-running loops.

**Notes**
- `break` only exits **one** loop level. In nested loops, it leaves the inner loop; the outer loop continues unless you also break there (via a flag, another `break`, or returning from a function).
- `continue` is different: it **skips to the next iteration** of the same loop instead of leaving it.
- There `for ... else`: the `else` block runs **only if the loop didn’t hit `break`**.

In [ ]:
import numpy as np

eeg_window = np.array([0.12, 0.28, 0.31, 0.95, 0.42, 0.38])
threshold = 0.9

for i, v in enumerate(eeg_window):
    if v > threshold:
        print(f"Peak detected at sample {i}: {v:.2f}")
        break       # stop scanning as soon as we find the first element over threshold
else:
    print("No peaks above threshold in this window.")

In [29]:
import numpy as np

step = 0
safety_cap = 100

while True:  # open-ended; we'll exit via 'break'
    v = np.random.rand()    # new sample in [0, 1)
    step += 1

    if v > 0.995:
        print(f"High-signal event at step {step} (v={v:.3f}). Stopping.")
        break               # exit as soon as the event occurs

    if step >= safety_cap:
        print("Safety cap reached; stopping to avoid an endless loop.")
        break               # defensive programming

Safety cap reached; stopping to avoid an endless loop.


## Indentation in Python: why it matters (a lot)

Python uses **indentation to define code blocks** — there are no `{}` braces like in other programming languages like C/C++/C#.
The amount and placement of indentation determine **which statements belong to a given block** (e.g., under a `for`, `while`, `if`, etc.). Getting indentation wrong often won’t raise a syntax error; instead, your code may **run but compute the wrong result**. 

In [ ]:
numbers = [5, 1, 3, 4, 2]

total = 0
count = 0
for num in numbers:
    total += num
# The following line is incorrectly indented; it runs once after the loop
count += 1  

average = total / count
print("Wrong average (due to indentation):", average)  # 15.0 (incorrect)

In [ ]:
numbers = [5, 1, 3, 4, 2]

total = 0
count = 0
for num in numbers:
    total += num
    count += 1  # correctly indented: runs once per element

average = total / count
print("Correct average:", average)  # 3.0

In [ ]:
numbers = [5, 1, 3, 4, 2]
number_to_find = 4

found = False
index = None

for i, num in enumerate(numbers):
    if number_to_find == num:
        found = True
        index = i
        print("True")
        break
    else:
        # Incorrect: this 'else' is tied to each iteration
        print("False")

True


In [32]:
numbers = [5, 1, 3, 4, 2]
number_to_find = 6

found = False
index = None

for i, num in enumerate(numbers):
    if number_to_find == num:
        found = True
        index = i
        print("True")
        break
else:
    # Incorrect: this 'else' is tied to each iteration
    print("False")

False


## Dictionaries

Dictionaries in Python are _unordered collections of items_. Each item is a **key-value** pair, where each unique key maps to a specific value.

Think of a dictionary as a real-world dictionary where a word (the key) is used to find its definition (the value).

They’re ideal when you need to label data and later retrieve or iterate over those labeled pieces. 
Unlike lists, which are indexed by numerical position, dictionaries are indexed by their keys, allowing for quick and intuitive data retrieval.

### Creating dictionaries

A **dictionary** in Python is created using curly braces `{}` with **key–value pairs** separated by a colon.

- Keys must be:
  - **Immutable** → value cannot change once created  
    (e.g., strings, numbers, tuples of immutables, booleans, `None`)  
  - **Hashable** → must have a stable hash value so Python can find it quickly in the dictionary

  Valid key examples
  - `"name"` (string)  
  - `1`, `3.14` (numbers)  
  - `(1, 2)` (tuple of immutables)  
  - `True`, `False` (booleans)  
  - `None`  

  Invalid key examples
  - `[1, 2, 3]` (list)  
  - `{"a": 1}` (dictionary)

- Values can be **any type**: numbers, strings, lists, sets, dictionaries, or even custom objects.

