# ICN Programming Course

<p align="center">
    <img width="500" alt="image" src="https://github.com/Lenakeiz/ICN_Programming_Course/blob/main/Images/cog_neuro_logo_blue_png_0.png?raw=true">
</p>

---

# **WEEK 1** - Exercises

## [1] Variables and Arithmetic
Generate three numeric variables `a`, `b`, and `c` with values of 2, 3 and 4, respectively.

Then compute the following:

$$x = \frac{a+c}{b}$$
$$y = \frac{b\,(a+\sqrt{c})}{a}$$
$$z = \frac{x}{a\,b}$$

> **Tip:** you can import the `math` python library for not basic arithmetic operations. 

In [1]:
import math

# Given
a, b, c = 2, 3, 4

# Computations
x = (a + c) / b
y = (b * (a + math.sqrt(c))) / a
z = x / (a * b)

print(f"a={a}, b={b}, c={c}")
print(f"x = (a+c)/b = {x}")
print(f"y = (b*(a + sqrt(c)))/a = {y}")
print(f"z = x/(a*b) = {z}")

a=2, b=3, c=4
x = (a+c)/b = 2.0
y = (b*(a + sqrt(c)))/a = 6.0
z = x/(a*b) = 0.3333333333333333


## [2] Two 3×3 Matrices, Element‑wise and Matrix Product
Generate two 3×3 matrices `mat1` and `mat2` (arbitrary integers). Compute their element‑wise product and matrix product, storing the results in `product1` and `product2`. 

In [2]:
import numpy as np

# Example 3x3 integer matrices
mat1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

mat2 = np.array([[9, 8, 7],
                 [6, 5, 4],
                 [3, 2, 1]])

# Element-wise product
product1 = mat1 * mat2

# Matrix product
product2 = np.dot(mat1,mat2)  # or np.matmul(mat1, mat2)

print("mat1 =\n", mat1)
print("mat2 =\n", mat2)
print("product1 (element-wise) =\n", product1)
print("product2 (matrix product) =\n", product2)

mat1 =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
mat2 =
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
product1 (element-wise) =
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
product2 (matrix product) =
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## [3] Generate the following wequences with specific steps
- From 60 to 3600 in steps of 60
- From 10 down to 1 in steps of −1
- From 1 to 365 in steps of 7
- From 365 to 3650 in steps of 365

> **Tip:** you might need to use the `range` which works the same as **slicing**

In [ ]:
s1 = list(range(60, 3600 + 60, 60))
s2 = list(range(10, 0, -1))
s3 = list(range(1, 365 + 1, 7))
s4 = list(range(365, 3650 + 365, 365))

print("s1 (60..3600 step 60): length =", len(s1), "; first 10 ->", s1[:10], "; last 5 ->", s1[-5:])
print("s2 (10..1 step -1):", s2)
print("s3 (1..365 step 7): length =", len(s3), "; first 10 ->", s3[:10], "; last 5 ->", s3[-5:])
print("s4 (365..3650 step 365):", s4)

## [4] Modify Matrix Entries
- Change the first row of `mat1` so all entries are 5.
- Change the first column of `mat2` to the numbers 1, 2, 3.
- Change the entry in the third row, third column of `mat2` to a `null` value `nan`.

> **Tip:** `nan` stands for _"not a number"_ and is the overall way to get an empty values in data variables. 
You can use `np.nan`

In [ ]:
import numpy as np

# Recreate example matrices (so this cell is self-contained)
mat1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]], dtype=float)

mat2 = np.array([[9, 8, 7],
                 [6, 5, 4],
                 [3, 2, 1]], dtype=float)

# Changes
mat1[0, :] = 5
mat2[:, 0] = [1, 2, 3]
mat2[2, 2] = np.nan

print("mat1 after change first row to 5s =\n", mat1)
print("mat2 after column/entry changes =\n", mat2)

## [5] Python list
- Create a one‑column collection with your name, age, and place of birth as three separate entries. 
- Do the same, but in a row

In [3]:
name = "Alex Example"
age = 29
place_of_birth = "Bristol"

# One-column collection (like a MATLAB 'cell array' first column)
column_list = [[name], [age], [place_of_birth]]  # 3x1 nested list
column_row = [name, age, place_of_birth]

# 'Structure' analogue: a dict
myData = {
    "name": name,
    "age": age,
    "place_of_birth": place_of_birth
}

print("info column (3x1):", column_list)
print("info row (1x3):", column_row)

info column (3x1): [['Alex Example'], [29], ['Bristol']]
info row (1x3): ['Alex Example', 29, 'Bristol']


## [6] Means and Standard Deviation
- Compute the mean of each **row** and **column** in `mat1` → `row_mean`, `col_mean`.
- Compute the standard deviation of **all** entries in `mat1`.
- Compute the mean of **all** entries in `mat2`, **ignoring** the `NaN` values.

> **Tip:** you can use the `axis` optional variable when calling the numpy functions like `np.mean(axis=1)`.
Check the numpy documentation to see what corresponds to row or columns.

In [4]:
import numpy as np

# Define matrices (with the same shapes as before)
mat1 = np.array([[5, 5, 5],   # first row set to 5s (as in exercise 4 result)
                 [4, 5, 6],
                 [7, 8, 9]], dtype=float)

mat2 = np.array([[1, 8, 7],
                 [2, 5, 4],
                 [3, 2, np.nan]], dtype=float)  # (3,3) as NaN

# Row and column means for mat1
row_mean = mat1.mean(axis=1)
col_mean = mat1.mean(axis=0)

# Std of all entries in mat1 (population std, ddof=0)
std_all = mat1.std()

# Mean of all entries in mat2, ignoring NaN
mean_mat2_ignore_nan = np.nanmean(mat2)

print("mat1 =\n", mat1)
print("row_mean =", row_mean)
print("col_mean =", col_mean)
print("std (all entries in mat1) =", std_all)
print("\nmat2 =\n", mat2)
print("mean(mat2) ignoring NaN =", mean_mat2_ignore_nan)

mat1 =
 [[5. 5. 5.]
 [4. 5. 6.]
 [7. 8. 9.]]
row_mean = [5. 5. 8.]
col_mean = [5.33333333 6.         6.66666667]
std (all entries in mat1) = 1.5634719199411433

mat2 =
 [[ 1.  8.  7.]
 [ 2.  5.  4.]
 [ 3.  2. nan]]
mean(mat2) ignoring NaN = 4.0
