# ICN Programming Course

<p align="center">
    <img width="500" alt="image" src="https://github.com/Lenakeiz/ICN_Programming_Course/blob/main/Images/cog_neuro_logo_blue_png_0.png?raw=true">
</p>

---

# **WEEK 1** - Python Intro, first script, variables, arithmetic, lists

## How to run this notebook & scripts

### In Jupyter Notebooks
> **Before you start (VS Code): Select a Python kernel/interpreter**
- Run a cell with **⇧+Enter** (or use the **Run** button in the toolbar).
- Execution is **top-to-bottom**: if a cell depends on variables defined above, run the earlier cells first.
- If you see errors like `NameError: name 'x' is not defined`, it often means a required cell wasn’t run yet.
- To restart a stuck session: **Kernel → Restart** (then re-run cells in order).

### Our first Python Program (`hello_world.py`)

1. **Create a file** named `hello_world.py` in your project folder.
2. **Add the code** below to the file:
   ```python
   print("Hello Python world!")
   ```
3. **Run it**  
   - **VS Code**: *Run → Run Without Debugging* (or press `Ctrl+F5`/`⇧F5` depending on your setup).  
   - **Terminal**:  
     ```cmd
     python hello_world.py
     ```

## Variables & reassignment
`print(...)` tells Python to display whatever is inside the parentheses. When you bind text to a variable (for example, `welcome_message`) and later **reassign** it, Python will print the variable’s **current** value. Start simple: define a variable, print it, change it, and print again.  
*Tip:* If you see a `NameError`, a name is misspelled or used before it’s defined—check the line number in the traceback.

In [1]:
welcome_message = "Welcome to the ICN programming course"
print(welcome_message)
welcome_message = "Welcome to the ICN programming course, again!"
print(welcome_message)

Welcome to the ICN programming course
Welcome to the ICN programming course, again!


## f-strings (inserting values into text)
**f-strings** let you place variable values directly inside a string: put `f` before the opening quote and wrap names in `{}`. Python replaces each name with its value when the string is displayed. You can also call methods inside the braces for nicer formatting, e.g., `{region.title()}`.

In [2]:
region = "hippocampus"; subj = 12
print(f"Subject {subj}: region = {region.title()}")

Subject 12: region = Hippocampus


## Concatenation (`+`)
You can build messages by **concatenating** strings with `+` (for example, `task + " - " + modality`). As messages grow or need formatting, **f-strings** are clearer and less error‑prone because they interpolate values directly and read like the final output.

In [3]:
#concatenation
task, modality = "n-back", "fMRI"
label = task + " - " + modality  # "n-back - fMRI"

## Changing case with string methods
Use `.title()` for Title Case, `.upper()` for uppercase, and `.lower()` for lowercase. These are helpful for normalizing user input or presenting labels consistently (e.g., brain region names). String methods return **new** strings and don’t modify the original value in place.

In [4]:
ec_label = "entorhinal cortex"
print(ec_label.title())
pfc_label = "prefrontal"
print(pfc_label.upper())     
print(pfc_label.lower())

Entorhinal Cortex
PREFRONTAL
prefrontal


## Tabs and newlines in output
Use escape sequences to organize output: `\t` inserts a **tab** and `\n` inserts a **newline**. Combine them to format quick tables or multi‑line readouts (e.g., headers followed by values on the next line).

In [5]:
print("ID\tAge\nS01\t23")

ID	Age
S01	23


## Trimming extra whitespace
Programs treat `'S01'` and `'  S01  '` as different strings. Clean up leading/trailing spaces with `.lstrip()`, `.rstrip()`, or `.strip()`. If you want to keep the cleaned value, assign it back to a variable.

In [6]:
subject_name = "  S01  "
print(subject_name.strip())
print(subject_name.lstrip())
print(subject_name.rstrip())

S01
S01  
  S01


Use `.removeprefix("sub_")` to drop a known prefix from an identifier like `"sub_1"`. To use the remainder numerically (e.g., a subject ID), convert it with `int(...)`. The original string stays unchanged unless you reassign it.

In [7]:
subject_name = "sub_1"
subject_num = int(subject_name.removeprefix("sub_"))
print(subject_num)

1


## Working with Numbers

Numbers can represent counts or measurements. Python’s core numeric types are:

- **Integers (`int`)** - whole numbers, positive or negative, without a decimal point. Useful for counters, loop indices, and sizes.  

- **Floats (`float`)** - numbers with a decimal point, also known as floating-point numbers. Floats are used for continuous measurements and values that may have fractional parts (timing, rates, averages).

### Arithmetic in Python (with neuroscience-inspired examples)

Python supports all the standard arithmetic operators:

- `+` **Addition** - combine values  
- `-` **Subtraction** - calculate differences  
- `*` **Multiplication** - scale one value by another  
- `/` **Division** (with `%` remainde) - compute ratios or rates (compute remainders)
- `**` **Exponential** - compute exponential (one number elevated by another)

In [8]:
spikes_trial1 = 45
spikes_trial2 = 52
total_spikes = spikes_trial1 + spikes_trial2
diff_spikes = spikes_trial2 - spikes_trial1
print("Total spikes:", total_spikes)
print("Difference:", diff_spikes)

Total spikes: 97
Difference: 7


In [ ]:
neurons = 100
trials = 20
recordings = neurons * trials
print("Total recordings:", recordings)

In [ ]:
rt_ms = 320
rt_s = rt_ms / 1000
print("Reaction time (s):", rt_s)


In [ ]:
samples = 1050
window = 200
windows = samples // window    # full 200-sample windows
remainder = samples % window   # leftover samples
print("Windows:", windows, "| Remainder:", remainder)

In [ ]:
arena_size_cm = 10
bin_size = 2    # cm
grid_dim = arena_size_cm // bin_size   # 10 cm / 2 cm = 5 bins per axis
n_bins = grid_dim ** 2                 # 25 bins total
print("Number of bins in grid:", n_bins)

# Lists 
A list in Python is an **ordered collection of items**. This means the order in which you put items into a list is maintained, and you can access items based on their position (or index). Lists are also very flexible:

*   They can hold items of **different data types** within the same list (though typically lists often hold items of the same type, like a list of numbers or a list of strings).
*   They are **mutable**, meaning you can change the contents of a list after it's been created – you can add, remove, or modify items.

To define a list in Python you use the `[]` operator

Here are some examples of how lists can be used to represent data:

*   **Spike Times:** A list of timestamps (in milliseconds or seconds) when a neuron fired.
    `spike_times = [10.5, 15.2, 22.1, 30.0, 35.8]`
*   **Neuron IDs:** A list of unique identifiers for a group of neurons.
    `neuron_ids = [101, 105, 112, 203]`
*   **Experimental Conditions:** A sequence representing the order of different conditions presented in an experiment.
    `experimental_conditions = ['stim_A', 'stim_B', 'baseline', 'stim_A']`
*   **Firing Rates across Trials:** A list where each element is the firing rate recorded during a specific trial.
    `firing_rates_per_trial = [55.6, 62.1, 48.9, 70.5]`

Understanding how to work with lists is crucial for handling and analyzing sequential and grouped data in neuroscience. We'll now explore some basic operations you can perform on lists.

In [ ]:
# A list of integers indicating neuron IDs in a recording session.
neuron_ids = [101, 105, 112, 203]
print(neuron_ids)

In [ ]:
# A list of timestamps (in milliseconds or seconds) when a neuron fired.
spike_times = [10.5, 15.2, 22.1, 30.0, 35.8]
print(spike_times)

In [ ]:
# A sequence representing the order of different conditions presented in an experiment.
experimental_conditions = ['baseline', 'fixation_time', 'condition_A', 'condition_B']
print(experimental_conditions)

In [1]:
# In Python lists are not fixed type, so you can mix types, but it's not recommended.
mixed_list = [101, 'condition_A', 15.2, True]
print(mixed_list)

[101, 'condition_A', 15.2, True]


## Accessing List Elements

Since lists are ordered collections, each item in a list has a specific position or **index**. In Python, indexing is **zero-based**, meaning the first element is at index `0`, the second at index `1`, and so on.

You can access individual elements by placing the index in square brackets `[]` after the list's name.

Python also supports **negative indexing**. Negative indices count from the end of the list:

*   `[-1]` refers to the last element.
*   `[-2]` refers to the second-to-last element, and so on.

Slicing lets you extract, copy, or modify **runs of items** in a sequence. The general form is:

```
seq[start:end:step]
```

- **`start`**: index to begin at (inclusive). Defaults to `0`.
- **`end`**: index to stop before (exclusive). Defaults to lenght of the list.
- **`step`**: stride between elements (default `1`). Can be negative.

In [ ]:
neuron_ids = [101, 105, 112, 203, 245, 302, 410, 512]

print(neuron_ids[0])    # First element (index 0)
print(neuron_ids[2])    # Third element (index 2)   
print(neuron_ids[-1])   # Last element (index -1)
print(neuron_ids[-3])   # Third-to-last element (index -3)

# Slicing
print(neuron_ids[2:5])  # start at 2, stop before 5
print(neuron_ids[:3])   # from beginning
print(neuron_ids[4:])   # to the end
print(neuron_ids[::2])  # every 2nd element
print(neuron_ids[::-1]) # reversed


101
112
512
302
[101, 105, 112]


[512, 410, 302, 245, 203, 112, 105, 101]

## Modifying a list

Lists are mutable, which means you can change their contents after they have been created.

You can change the value of an item in a list by referring to its index and assigning a new value. This is similar to accessing elements, but instead of just retrieving the value, you are overwriting it.

In [6]:
spike_times = [10.5, 15.2, 22.1, 30.0, 35.8]
third_element = spike_times[2]
third_element = 25.0
spike_times[2] = third_element # can also be done in one step: spike_times[2] = 25.0
print(spike_times)

[10.5, 15.2, 25.0, 30.0, 35.8]


### Adding elements

You can add new elements to a list using several methods:

*   **`append()`:** This method adds an item to the *end* of the list. It's the simplest way to add a single item.
*   **`insert()`:** This method allows you to add an item at any specific position in the list. You provide the index where you want to insert the item, followed by the item itself. The existing items at that index and beyond are shifted to the right.

In [7]:
spike_times.append(40.1)
spike_times.insert(2, 20.0) # Insert 20.0 at index 2
print(spike_times)


[10.5, 15.2, 20.0, 25.0, 30.0, 35.8, 40.1]


## Removing elements

You can remove elements from a list in several ways:

*   **`del` statement:** If you know the index of the item you want to remove, you can use the `del` statement.
*   **`pop()` method:** This method removes the item at a specific index and returns the value of that item. If you don't specify an index, `pop()` removes and returns the *last* item in the list. This is useful when you want to remove an item and also use its value.
*   **`remove()` method:** If you know the *value* of the item you want to remove but not its index, you can use the `remove()` method. This method removes the *first* occurrence of the specified value.

In [ ]:
del spike_times[1] # Remove the element at index 1 (15.2)
print(spike_times)

last_spike = spike_times.pop() # Removes and returns the last element (40.1)
print("Popped last spike:", last_spike)
first_spike = spike_times.pop(0) # Removes and returns the first element (10.5)
print("Popped first spike:", first_spike)

# removing previously inserted element
spike_times.remove(20.0) # Removes the first occurrence of the value 20

## Organising lists

You can rearrange the elements of a list using sorting methods.

The `.sort()` method changes the order of the list *permanently*.
It sorts the list in ascending order by default. If you want to sort in descending order, you can pass the argument `reverse=True` inside the parentheses.
This method modifies the original list and does not return a new list.

In [9]:
neuron_ids = [101, 205, 302, 203]
neuron_ids.sort()
print(neuron_ids)
neuron_ids.sort(reverse=True) 
print(neuron_ids)

[101, 203, 205, 302]
[302, 205, 203, 101]


If you require to this operation temporarily, you can then use `sorted()`. 
The `sorted()` function is different from the `.sort()` method because it does *not* change the original list.
Instead, it returns a *new* list containing the elements of the original list in sorted order. Like `.sort()`, it sorts in ascending order by default, and you can pass `reverse=True` for descending order.
Use `sorted()` when you want to display a list in sorted order without affecting the original order.

In [11]:
neuron_ids = [101, 205, 302, 203]
sorted_neurons = sorted(neuron_ids)
print("Original list:", neuron_ids)
print("Sorted list:", sorted_neurons)

Original list: [101, 205, 302, 203]
Sorted list: [101, 203, 205, 302]


The `.reverse()` method permanently reverses the *original* order of the elements in a list.
It doesn't sort the list in alphabetical or numerical order; it simply flips the sequence of items.

In [ ]:
neuron_ids = [101, 205, 302, 203]
neuron_ids.reverse()
print(neuron_ids)

## Checking the lenght of a list

To check the lenght of a list you can simply use the `len()` function

In [13]:
neuron_ids = [101, 205, 302, 203]
print(f"Number of neurons: {len(neuron_ids)}")

Number of neurons: 4


# Numpy arrays

While standard Python lists are versatile for storing collections of items, they are not optimized for numerical operations, especially when dealing with large datasets. 
For efficient numerical computation in Python, the **NumPy** library comes really handy.

## Introducing NumPy Arrays

At the core of NumPy is the **ndarray** (n-dimensional array) object.
NumPy arrays are similar to Python lists in that they can hold collections of items, but they have crucial differences:

*   **Homogeneous Data Type:** Unlike Python lists, all elements in a NumPy array must be of the *same* data type (e.g., all integers, all floats).

*   **Optimized for Numerical Operations:** NumPy provides a wide range of mathematical functions and operations that are highly optimized and executed much faster than equivalent operations on standard Python lists, particularly for large datasets.

*   **N-Dimensional:** NumPy arrays can have any number of dimensions, making them suitable for representing various types of data:
    *   **1D arrays (vectors):** Use for ordered sequences such as time series, binned spike counts over time, a list of trial onsets.
    *   **2D arrays (matrices):** Ideal for representing data from multiple over time, connectivity matrices (neuron x neuron), or trials x time data.
    *   **Higher-dimensional arrays:** Use when each row is an observation and each column is a variable or time bin; e.g., trials × time spike raster, channels × time LFP/EEG, ROI × time BOLD signals, or neuron × neuron connectivity (square).



In [20]:
import numpy as np

# 1d array
membrane_potential_trace = np.array([-68.5, -68.2, -67.9, -67.0, -65.5, -63.1, -60.8, -58.5, -55.0, -54.8, -55.1, -58.0, -62.5])
print("1D NumPy Array (Membrane Potential Trace):")
print(membrane_potential_trace)
print("-" * 30)

# 2d array over multiple trials
membrane_potential_trials = np.array([
    [45.2, 58.1, 39.5, 62.8, 50.1],  # Trial 1 rates
    [50.9, 63.7, 42.1, 68.5, 55.3],  # Trial 2 rates
    [48.1, 60.5, 40.8, 65.3, 52.9]   # Trial 3 rates
])
print("2D NumPy Array (Membrane Potential Matrix - Trials x Potentials):")
print(membrane_potential_trials)


1D NumPy Array (Membrane Potential Trace):
[-68.5 -68.2 -67.9 -67.  -65.5 -63.1 -60.8 -58.5 -55.  -54.8 -55.1 -58.
 -62.5]
------------------------------
2D NumPy Array (Membrane Potential Matrix - Trials x Potentials):
[[45.2 58.1 39.5 62.8 50.1]
 [50.9 63.7 42.1 68.5 55.3]
 [48.1 60.5 40.8 65.3 52.9]]


## Accessing Numpy arrays

Just like with Python lists, we can access individual elements or subsets of elements within NumPy arrays using **indexing** and **slicing**.

For 2D arrays (matrices), you need to specify both the **row index** and the **column index**. 
You can do this by separating the indices with a comma inside the square brackets: `[row_index, column_index]`. This enables you to also do **slicing**.

`Lists` enables you to create 2D arrays, using `[][]`, however, NumPy's indexing and slicing capabilities are more powerful and flexible, especially for multi-dimensional arrays.


In [33]:
firing_rates_np = np.array([
    [55.2, 60.1, 48.5, 70.3, 58.9],  # Trial 1
    [60.5, 65.8, 52.1, 75.9, 62.3],  # Trial 2
    [58.1, 63.5, 50.4, 72.1, 60.8],  # Trial 3
    [62.3, 67.1, 55.0, 78.5, 65.1],  # Trial 4
    [57.5, 62.9, 49.8, 71.0, 59.5],  # Trial 5
    [61.8, 66.5, 53.5, 77.8, 64.0],  # Trial 6
    [59.0, 64.2, 51.1, 73.5, 61.5],  # Trial 7
    [63.1, 68.0, 56.2, 79.1, 66.3],  # Trial 8
    [56.8, 61.5, 47.9, 69.5, 57.0],  # Trial 9
    [64.5, 69.2, 57.0, 80.0, 67.5]   # Trial 10
])

print("Original NumPy Array (Firing Rates):")
print(firing_rates_np)
print("-" * 40)

np_trial7_data = firing_rates_np[6, :]
print("Trial 7 Data (Firing Rates):")
print(np_trial7_data)
print("-" * 40)


Original NumPy Array (Firing Rates):
[[55.2 60.1 48.5 70.3 58.9]
 [60.5 65.8 52.1 75.9 62.3]
 [58.1 63.5 50.4 72.1 60.8]
 [62.3 67.1 55.  78.5 65.1]
 [57.5 62.9 49.8 71.  59.5]
 [61.8 66.5 53.5 77.8 64. ]
 [59.  64.2 51.1 73.5 61.5]
 [63.1 68.  56.2 79.1 66.3]
 [56.8 61.5 47.9 69.5 57. ]
 [64.5 69.2 57.  80.  67.5]]
----------------------------------------
Trial 7 Data (Firing Rates):
[59.  64.2 51.1 73.5 61.5]
----------------------------------------


To get a column, here is where 

For 2D arrays (matrices), you need to specify both the **row index** and the **column index**. 
You can do this by separating the indices with a comma inside the square brackets: `[row_index, column_index]`. This enables you to also do **slicing**.

In [ ]:

np_neuron4_data = firing_rates_np[:, 3] # NOTE For a list, we need a loop or "list comprehension" to get a column (we are going to see an example later)
print("Neuron 4 Data (Firing Rates):")
print(np_neuron4_data)
print("-" * 40)

# Select trials where the firing rate of Neuron 1 (index 0) is above 60 Hz
condition = firing_rates_np[:, :] > 60
print("Boolean condition (Neuron 1 > 60 Hz):")
print(condition)
print("-" * 40)